### ISSUE TITLE
Align pagination and "Showing 1-20 of XYZ" 

### ISSUE THREAD

**Issue by danoc** [bupipedream/Public-Salaries#13]
Notice that the pagination and "Showing 1-20 of XYZ" is out of line? I'd like to move the pagination to the left part of the table (no center align) and have it vertically align with the results information.

To do this, you can wrap both of those in a `<footer>`. Read up on CSS floats and float one of those two parts.

**Comment by ghost** [comment]
Would you mind if I did this the same way as I did for the search bar? That is, us Bootstrap's fluid layouts/grid system rather than floating the divs manually? I've been playing with the responsive design bookmarklet, and it tends to flow better this way.

**Comment by danoc** [comment]
Sorry @HalfGearHeart, just saw this now! Looks like you got it working though.

**Comment by danoc** [comment]
Looks like the same thing is now broken. Can someone take a look?
