### ISSUE TITLE
Fix header so that search adapts to smaller screens

### ISSUE THREAD

**Issue by danoc** [bupipedream/Public-Salaries#16]
![Screen Shot 2013-01-26 at 1 12 59 PM](https://f.cloud.github.com/assets/916038/100049/10a00e20-67e4-11e2-98db-d026153bf11c.png)

Notice how the search bar falls under the header on smaller screens? I'd like for it to fit inline with the header. I'd recommend looking at Bootstrap's documentation and responsive CSS.

**Comment by ghost** [comment]
Oh, cool. I was just gonna get to this. It'll be done by tomorrow, gotta drive up to Bing in a few.

Also, by fit inline you mean underneath and aligned-left?
