### ISSUE TITLE
Get total number of rows in database to use in pagination

### ISSUE THREAD

**Issue by danoc** [bupipedream/Public-Salaries#19]
You'll have to create a separate function called `countNumRows` and use `num_rows` on `$query` in CodeIgniter.

Please try to figure this one out by reading the CodeIgniter documentation since I'm super busy this week!

Also, don't be afraid to commit something you're not sure about. I'll comment on the code and we'll fix it before going live.

**Resources:**
- Models - http://ellislab.com/codeigniter/user-guide/general/models.html
- Query Results - http://ellislab.com/codeigniter/user-guide/database/results.html

**Comment by JustinPattek** [comment]
on it
