### ISSUE TITLE
Pass number of results found to view 

### ISSUE THREAD

**Issue by danoc** [bupipedream/Public-Salaries#20]
We have to modify the "Showing 1-20 of XYZ" message since we can't assume that there will always be 20 results. For example, if we're searching for "Smith" and there are only 13 Smiths', then it can't say 1-20.

Change the functions in the model to return the `$query` object and pass the `result()` and `num_rows()` functions of `$query` from the controller to the view.

Then, in the view, edit the 1-20 part to display the correct values. The XYZ will be fixed by someone else.

Also, please try to figure this one out by reading through the documentation. I don't have much time in the next few days, so, if you get it working, just commit the code and I'll comment on it.

**Resources:**
- Models - http://ellislab.com/codeigniter/user-guide/general/models.html
- Query Results - http://ellislab.com/codeigniter/user-guide/database/results.html

**Comment by DerekParry** [comment]
I'm feeling up to the challenge. I'm gonna take a stab.

**Comment by JustinPattek** [comment]
I think I have this finished, I'm going to push my code and you can see if you like my implementation

**Comment by JustinPattek** [comment]
I just noticed that my code sends page numbers 0 - 20 to the view when it probably should be 1 - 20. I am too tired to fix it right now so this issue isn't closed

**Comment by danoc** [comment]
@JustinPattek - Thanks! Just make that quick fix and commit then we'll close it.
