### ISSUE TITLE
Remove index.php from URL

### ISSUE THREAD

**Issue by danoc** [bupipedream/Public-Salaries#22]
Read through the section on `index.php` and run through that part. For more information, Google ".htaccess" and "codeigniter index.php" to understand what they are talking about. It might not seem like an issue on our website, but navigate to `path/to/project/index.php/main/index/` and you'll see what I'm talking to.

**Note:** Don't delete the index.php file. That'll break the website. You're simply telling the server to hide index.php from the URLs.

**Resources:**
- URLs - http://ellislab.com/codeigniter/user-guide/general/urls.html

**Comment by DerekParry** [comment]
So here's what I've got: 
1. I think you can remove the extension in "config/config.php" by setting the last part of "$config['index_page'] = 'index.php';" to a null string.
2. Apparently I can redirect everything to the index.php page with the .htaccess code from Dan's link. I created a .htaccess file in the project's directory
3. To use the code on Dan's link on Windows, you have to change permissions in WAMP
   (Search "LoadModule rewrite_module modules/mod_rewrite.so" and uncomment that line)
4. When I do item 2, the files show up all listed out, and it doesn't look like it's redirecting bad links (such as "path/to/project/index.php/main/index/")
5. When I do 1 along with 2, it looks as if nothing changed from the description of 4
6. When I do 1 alone, it seems as if nothing changed from the original site before these changes
